---
- hosts: all 
  become: yes 
  tasks:
  
  - name: Create results dir for ls
    shell:
      cmd: mkdir -p /home/vagrant/testbench/results/ls
      chdir: /home/vagrant/
      
  - name: Create results dir
    shell:
      cmd: mkdir -p /home/vagrant/testbench/results/diff
      chdir: /home/vagrant/
      
  - name: Create results dir
    shell:
      cmd: mkdir -p /home/vagrant/testbench/results/file
      chdir: /home/vagrant/
  
  # ls
  - name: Analyze ls
    shell:
      cmd: analyze_binary.sh ls .0.5.precodegen.bc
      chdir: /home/vagrant/temporal-specialization/

  - name: Copy results from ls
    shell:
      cmd: ./copy_results.sh ls
      chdir: /home/vagrant/temporal-specialization/

 - name: Cleanup after ls
    shell:
      cmd: ./cleanup.sh
      chdir: /home/vagrant/temporal-specialization/
      
  # diff
  - name: Analyze diff
    shell:
      cmd: analyze_binary.sh diff .0.5.precodegen.bc
      chdir: /home/vagrant/temporal-specialization/

  - name: Copy results from diff
    shell:
      cmd: ./copy_results.sh diff
      chdir: /home/vagrant/temporal-specialization/

 - name: Cleanup after diff
    shell:
      cmd: ./cleanup.sh
      chdir: /home/vagrant/temporal-specialization/
      
  # file
  - name: Analyze ls
    shell:
      cmd: analyze_binary.sh file .0.5.precodegen.bc
      chdir: /home/vagrant/temporal-specialization/

  - name: Copy results from file
    shell:
      cmd: ./copy_results.sh file
      chdir: /home/vagrant/temporal-specialization/

 - name: Cleanup after file
    shell:
      cmd: ./cleanup.sh
      chdir: /home/vagrant/temporal-specialization/