---
- hosts: all 
  become: yes 
  tasks:
  - name: installing package dependencies
    apt: 
      name: 
        - autoconf
        - autopoint
        - gperf
      state: latest
      update_cache: true
      

  - name: Creating examples directory
    file:
      path: /home/vagrant/testbench
      state: directory
      
  - name: Cloning GNU coreutils
    git:
      repo: git://git.sv.gnu.org/coreutils
      dest: /home/vagrant/testbench/coreutils
      clone: yes
      update: yes
      
  - name: Download und unarchive Diffutils-3.8
    ansible.builtin.unarchive:
      src: https://ftp.gnu.org/gnu/diffutils/diffutils-3.8.tar.xz
      dest: /home/vagrant/testbench/
      remote_src: yes
      
  - name: Download und unarchive Fileutils-5.39
    ansible.builtin.unarchive:
      src: http://ftp.astron.com/pub/file/file-5.39.tar.gz
      dest: /home/vagrant/testbench/
      remote_src: yes
# Change ownership of everything to user vagrant because ./configure shouldnt be run as root but logs are owned by root
  - name: Change ownership of everything to user vagrant
    shell:
      cmd: chown -R vagrant *
      chdir: /home/vagrant/
    
# this step needs to be done manually if clang-7 is not found 
  - name: Add to PATH
    copy:
      content: "export PATH=$PATH:/home/vagrant/temporal-specialization/llvm-7.0.0.src/build/bin"
      dest: "/etc/profile.d/my_path.sh"
      
  - name: Load profile changes in shell
    shell:
      cmd: source /etc/profile.d/my_path.sh
      chdir: /home/vagrant/

# coreutils for ls    
  - name: Configuring Coreutils and grabbing submodules
    shell:
      cmd: ./bootstrap
      chdir: /home/vagrant/testbench/coreutils  
    
# if this fails export temporal-specialization/llvm-7.0.0.src/build/bin to PATH
  - name: Configuring the Coreutils compiler for tempSpec
    shell:
      cmd: |
       export PATH=$PATH:/home/vagrant/temporal-specialization/llvm-7.0.0.src/build/bin
       ./configure AR=llvm-ar CC=clang-7 CXX=clang-7 LD=/usr/bin/ld CFLAGS="-flto -O0" CXXFLAGS="-flto -O0" LDFLAGS="-flto -Wl,-plugin-opt=save-temps"
      chdir: /home/vagrant/testbench/coreutils
      
  - name: Removing old make attempts
    shell:
      cmd: make clean
      chdir: /home/vagrant/testbench/coreutils
      
  - name: Compiling using max threads
    shell:
      cmd: make -j$(nproc)
      chdir: /home/vagrant/testbench/coreutils
      
  - name: Copying Bitcodes to temporal-specialization/bitcodes
    shell:
      cmd: find . -name "*.0.5.precodegen.bc" -exec cp {} /home/vagrant/temporal-specialization/bitcodes \;
      chdir: /home/vagrant/testbench/coreutils/src
      
  - name: Creating ls binary dir and copying binary
    shell:
      cmd: mkdir -p /home/vagrant/temporal-specialization/binaries/ls ; cp ls /home/vagrant/temporal-specialization/binaries/ls/
      chdir: /home/vagrant/testbench/coreutils/src

#diffutils for diff
  - name: Configuring Diffutils 
    shell:
      cmd: ./configure AR=llvm-ar CC=clang-7 CXX=clang-7 LD=/usr/bin/ld CFLAGS="-flto -O0" CXXFLAGS="-flto -O0" LDFLAGS="-flto -Wl,-plugin-opt=save-temps"
      chdir: /home/vagrant/testbench/diffutils-3.8


  - name: Compiling Diffutils
    shell:
      cmd: make -j$(nproc)
      chdir: /home/vagrant/testbench/diffutils-3.8

  - name: Copying Bitcodes to temporal-specialization/bitcodes
    shell:
      cmd: find . -name "*.0.5.precodegen.bc" -exec cp {} /home/vagrant/temporal-specialization/bitcodes \;
      chdir: /home/vagrant/testbench/diffutils-3.8/src
      
  - name: Creating diff binary dir and copying binary
    shell:
      cmd: mkdir -p /home/vagrant/temporal-specialization/binaries/diff ; cp diff /home/vagrant/temporal-specialization/binaries/diff/
      chdir: /home/vagrant/testbench/diffutils-3.8/src
      
#fileutils for file 
  - name: Configuring Fileutils 
    shell:
      cmd: ./configure AR=llvm-ar CC=clang-7 CXX=clang-7 LD=/usr/bin/ld CFLAGS="-flto -O0" CXXFLAGS="-flto -O0" LDFLAGS="-flto -Wl,-plugin-opt=save-temps"
      chdir: /home/vagrant/testbench/file-5.39

  - name: Compiling Fileutils
    shell:
      cmd: make -j$(nproc)
      chdir: /home/vagrant/testbench/file-5.39

  - name: Copying Bitcodes to temporal-specialization/bitcodes
    shell:
      cmd: find . -name "*.0.5.precodegen.bc" -exec cp {} /home/vagrant/temporal-specialization/bitcodes \;
      chdir: /home/vagrant/testbench/file-5.39/src
      
  - name: Creating file binary dir and copying binary
    shell:
      cmd: mkdir -p /home/vagrant/temporal-specialization/binaries/file ; cp file /home/vagrant/temporal-specialization/binaries/file/
      chdir: /home/vagrant/testbench/file-5.39/src