---
- hosts: all 
  become: yes 
  tasks:
  - name: installing package dependencies
    apt: 
      name: 
        - autoconf
        - autopoint
        - gperf
      state: latest
      update_cache: true
      
  # coreutils for ls
  - name: Creating examples directory
    file:
      path: /home/vagrant/simon-examples
      state: directory
      
  - name: Cloning GNU coreutils
    git:
      repo: git://git.sv.gnu.org/coreutils
      dest: /home/vagrant/simon-examples/coreutils
      clone: yes
      update: yess
      
  - name: Configuring Coreutils and grabbing submodules
    shell:
      cmd: ./bootstrap
      chdir: /home/vagrant/simon-examples/coreutils

  - name: Setting up PATH
    shell:
      cmd: export LLVM_DIR=/home/vagrant/temporal-specialization/llvm-7.0.0.src/build/bin; export PATH=$LLVM_DIR/:$PATH
      chdir: /home/vagrant/simon-examples/coreutils

      
  - name: Configuring the Coreutils compiler for tempSpec
    shell:
      cmd: ./configure AR=llvm-ar CC=clang-7 CXX=clang-7 LD=/usr/bin/ld CFLAGS="-flto -O0" CXXFLAGS="-flto -O0" LDFLAGS="-flto -Wl,-plugin-opt=save-temps"
      chdir: /home/vagrant/simon-examples/coreutils
      
  - name: Removing old make attempts
    shell:
      cmd: make clean
      chdir: /home/vagrant/simon-examples/coreutils
      
  - name: Compiling using max threads
    shell:
      cmd: make -j$(nproc)
      chdir: /home/vagrant/simon-examples/coreutils
      
  - name: Copying Bitcodes to temporal-specialization/bitcodes
    shell:
      cmd: find . -name "*.0.5.precodegen.bc" -exec cp {} /home/vagrant/temporal-specialization/bitcodes \;
      chdir: /home/vagrant/simon-examples/coreutils/src
      
  - name: Creating LS Bianry dir and copying binary
    shell:
      cmd: mkdir -p /home/vagrant/temporal-specialization/binaries/ls ; cp ls /home/vagrant/temporal-specialization/binaries/ls/
      chdir: /home/vagrant/simon-examples/coreutils/src
      
      #modifiy app.to.properties.json 